apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: server
        image: bckjob_worker:0.1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: REDIS_HOST     
            value: redis-service    
          - name: APP_HOST     
            value: http://app-service    